create extension if not exists pg_cron with schema extensions;

create table if not exists public.system_heartbeats (
  id bigint generated by default as identity primary key,
  source text not null default 'supabase-cron',
  note text not null default 'technical maintenance heartbeat',
  recorded_at timestamptz not null default now()
);

alter table public.system_heartbeats enable row level security;

drop policy if exists "admins read system heartbeats" on public.system_heartbeats;
create policy "admins read system heartbeats"
  on public.system_heartbeats
  for select
  to authenticated
  using (public.current_app_role() in ('admin', 'manager'));

create or replace function public.record_system_heartbeat()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1
    from public.system_heartbeats
    where recorded_at >= now() - interval '6 days'
  ) then
    insert into public.system_heartbeats (source, note)
    values ('supabase-cron', 'technical maintenance heartbeat');
  end if;
end;
$$;

revoke all on function public.record_system_heartbeat() from public;
revoke execute on function public.record_system_heartbeat() from anon;
revoke execute on function public.record_system_heartbeat() from authenticated;

do $$
begin
  if exists (
    select 1
    from cron.job
    where jobname = 'ic-system-heartbeat'
  ) then
    perform cron.unschedule('ic-system-heartbeat');
  end if;

  perform cron.schedule(
    'ic-system-heartbeat',
    '0 6 * * *',
    $job$select public.record_system_heartbeat();$job$
  );
end $$;

select public.record_system_heartbeat();
