create table if not exists public.system_heartbeats (
  id bigint generated by default as identity primary key,
  source text not null default 'external',
  note text not null default 'external maintenance heartbeat',
  recorded_at timestamptz not null default now()
);

alter table public.system_heartbeats enable row level security;

drop policy if exists "admins read system heartbeats" on public.system_heartbeats;
create policy "admins read system heartbeats"
  on public.system_heartbeats
  for select
  to authenticated
  using (public.current_app_role() in ('admin', 'manager'));
